# Generated by Django 5.2.17 on 2026-09-12 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(default='Kenya', max_length=80)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travelers', models.PositiveIntegerField(default=1)),
                ('base_amount', models.PositiveIntegerField()),
                ('fees', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourlink_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='MPESA', max_length=30)),
                ('status', models.CharField(default='PENDING', max_length=24)),
                ('merchant_reference', models.CharField(max_length=80, unique=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('starting_point', models.CharField(max_length=160)),
                ('ending_point', models.CharField(max_length=160)),
                ('duration_days', models.PositiveIntegerField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('price_per_person', models.PositiveIntegerField()),
                ('max_travelers', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=16)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.destination')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourlink_trips', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.tripcategory')),
            ],
            options={
                'ordering': ['-featured', 'departure_date'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.trip'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=180)),
                ('registration_number', models.CharField(max_length=40, unique=True)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('body_type', models.CharField(max_length=80)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=40)),
                ('fuel_type', models.CharField(max_length=40)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('four_by_four', models.BooleanField(default=False)),
                ('driver_included', models.BooleanField(default=False)),
                ('price_per_day', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.destination')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourlink_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourlink_reviews', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.booking')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.trip')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.vehicle'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'departure_date'], name='core_trip_status_a3ddd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('booking', 'author'), name='unique_booking_review'),
        ),
    ]
