import { Filter, SlidersHorizontal } from "lucide-react";
import { trips } from "@/lib/demo-data";
import { SearchPanel } from "@/components/search-panel";
import { TripCardView } from "@/components/ui";

export default async function TripsPage({ searchParams }: { searchParams: Promise<{ search?: string; destination?: string; category?: string; maxPrice?: string; minRating?: string; sort?: string }> }) {
  const params = await searchParams;
  const query = (params.search || params.destination || "").toLowerCase();
  let results = trips.filter(trip => (!query || `${trip.name} ${trip.destination} ${trip.category} ${trip.operator}`.toLowerCase().includes(query)) && (!params.category || trip.category === params.category) && (!params.maxPrice || trip.price <= Number(params.maxPrice)) && (!params.minRating || trip.rating >= Number(params.minRating)));
  if (params.sort === "price") results = [...results].sort((a, b) => a.price - b.price);
  if (params.sort === "rating") results = [...results].sort((a, b) => b.rating - a.rating);
  return <main className="min-h-screen bg-mist pb-24"><section className="bg-ink py-12 text-white sm:py-16"><div className="container-page"><p className="eyebrow text-sun">Find your next story</p><h1 className="display mt-2 text-4xl font-bold sm:text-6xl">Trips, made memorable.</h1><div className="mt-8 max-w-4xl"><SearchPanel compact /></div></div></section><div className="container-page py-10"><form className="mb-7 grid gap-3 rounded-2xl bg-white p-4 shadow-soft sm:grid-cols-2 lg:grid-cols-5"><select name="category" defaultValue={params.category || ""} className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs font-bold"><option value="">All categories</option>{["Safari", "Beach", "Wildlife", "Road Trip", "Adventure"].map(value => <option key={value}>{value}</option>)}</select><select name="maxPrice" defaultValue={params.maxPrice || ""} className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs font-bold"><option value="">Any price</option><option value="20000">Under KES 20,000</option><option value="30000">Under KES 30,000</option><option value="50000">Under KES 50,000</option></select><select name="minRating" defaultValue={params.minRating || ""} className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs font-bold"><option value="">Any rating</option><option value="4.5">4.5+ stars</option><option value="4.8">4.8+ stars</option></select><select name="sort" defaultValue={params.sort || ""} className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs font-bold"><option value="">Sort: Recommended</option><option value="price">Price: lowest first</option><option value="rating">Rating: highest first</option></select><button className="flex items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3 text-xs font-extrabold text-white"><SlidersHorizontal size={15} /> Apply filters</button></form><div className="mb-7 flex items-center justify-between gap-4"><p className="text-sm text-slate-500">{results.length} experiences found{query && <> for <strong className="text-ink">“{params.search || params.destination}”</strong></>}</p><a href="/compare" className="flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2.5 text-xs font-extrabold text-ink">Compare trips</a></div>{results.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{results.map(trip => <TripCardView key={trip.id} trip={trip} />)}</div> : <div className="rounded-3xl bg-white py-20 text-center"><Filter className="mx-auto text-sun" /><h2 className="mt-4 text-lg font-extrabold">No trips found yet</h2><p className="mt-2 text-sm text-slate-500">Try another destination or broaden your filters.</p></div>}</div></main>;
}
