import { PrismaClient, Role, VerificationLevel, ListingStatus, VerificationStatus, BookingStatus, BookingType, PaymentStatus } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();
const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`;
const destinations = [
  ["Nairobi", "nairobi", "Kenya's energetic capital and the gateway to the wild.", image("photo-1539650116574-75c0c6d73f6e")], ["Maasai Mara", "maasai-mara", "The golden home of big skies, big cats and the great migration.", image("photo-1516426122078-c23e76319801")], ["Amboseli", "amboseli", "Elephants moving through dust beneath Mount Kilimanjaro.", image("photo-1547970810-dc1eac37d174")], ["Tsavo", "tsavo", "Vast red-earth landscapes and wildlife in the wild east.", image("photo-1535338454770-8be927b5a00b")], ["Diani", "diani", "Warm water, white sand and the easy rhythm of the coast.", image("photo-1510414842594-a61c69b5ae57")], ["Mombasa", "mombasa", "A living blend of Swahili coast, history and ocean air.", image("photo-1589394815804-964ed0be2eb5")], ["Nakuru", "nakuru", "Rift Valley views, flamingos and cool green escapes.", image("photo-1547471080-7cc2caa01a7e")], ["Naivasha", "naivasha", "Lake days, acacia sunsets and quiet weekends away.", image("photo-1516026672322-bc52d61a55d5")], ["Mount Kenya", "mount-kenya", "High trails and alpine air on Africa's second highest mountain.", image("photo-1609198092458-38a293c7ac4b")], ["Samburu", "samburu", "A bold, beautiful north shaped by culture and open land.", image("photo-1535338454770-8be927b5a00b")], ["Watamu", "watamu", "Reefs, mangroves and a slower kind of blue.", image("photo-1507525428034-b723cf961d3e")], ["Lamu", "lamu", "Dhow sails, old streets and the softest island time.", image("photo-1500530855697-b586d89ba3ee")]
];
const tripNames = ["Mara Golden Hour Safari", "Diani Coast Reset", "Amboseli Under the Mountain", "Rift Valley Weekender", "Samburu: Wild North", "Tsavo Red Earth Escape", "Lake Naivasha Slow Weekend", "Mount Kenya Forest Trail", "Old Town & Ocean Stories", "Watamu Blue Water Days", "Lamu Island Unhurried", "Nairobi Food & Culture Walk", "Mara Family Adventure", "Diani Honeymoon Hideaway", "Kenya by Road: The Long Way"];
const tripImages = ["photo-1516426122078-c23e76319801", "photo-1510414842594-a61c69b5ae57", "photo-1547970810-dc1eac37d174", "photo-1547471080-7cc2caa01a7e", "photo-1535338454770-8be927b5a00b", "photo-1535338454770-8be927b5a00b", "photo-1516026672322-bc52d61a55d5", "photo-1609198092458-38a293c7ac4b", "photo-1589394815804-964ed0be2eb5", "photo-1507525428034-b723cf961d3e", "photo-1500530855697-b586d89ba3ee", "photo-1539650116574-75c0c6d73f6e", "photo-1516426122078-c23e76319801", "photo-1510414842594-a61c69b5ae57", "photo-1535338454770-8be927b5a00b"];

async function main() {
  await prisma.review.deleteMany(); await prisma.booking.deleteMany(); await prisma.tripImage.deleteMany(); await prisma.vehicleImage.deleteMany(); await prisma.trip.deleteMany(); await prisma.vehicle.deleteMany(); await prisma.destination.deleteMany(); await prisma.tripCategory.deleteMany(); await prisma.operatorProfile.deleteMany(); await prisma.vehicleOwnerProfile.deleteMany(); await prisma.travelerProfile.deleteMany(); await prisma.user.deleteMany();
  const passwordHash = await bcrypt.hash("TourLink123!", 12);
  const verifiedAt = new Date();
  await prisma.user.create({ data: { name: "TourLink Admin", email: "admin@tourlink.ke", phone: "254700000001", emailVerifiedAt: verifiedAt, phoneVerifiedAt: verifiedAt, approvalStatus: "APPROVED", passwordHash, role: Role.ADMIN, verificationLevel: VerificationLevel.TRUSTED } });
  const traveler = await prisma.user.create({ data: { name: "Amina Kariuki", email: "traveler@tourlink.ke", phone: "254700000002", emailVerifiedAt: verifiedAt, phoneVerifiedAt: verifiedAt, approvalStatus: "APPROVED", passwordHash, role: Role.TRAVELER, verificationLevel: VerificationLevel.VERIFIED, travelerProfile: { create: {} } } });
  const travelers = [traveler];
  for (let i = 2; i <= 4; i++) travelers.push(await prisma.user.create({ data: { name: ["Daniel Otieno", "Wanjiku Maina", "Sammy Kibet"][i - 2], email: `traveler${i}@tourlink.ke`, phone: `25470000000${i + 1}`, emailVerifiedAt: verifiedAt, phoneVerifiedAt: verifiedAt, approvalStatus: "APPROVED", passwordHash, role: Role.TRAVELER, travelerProfile: { create: {} } } }));
  const operators = []; const operatorNames = ["Savanna & Soul", "Coastline Collective", "Open Road Kenya", "Nia Adventures", "Wild Thread Expeditions"];
  for (let i = 0; i < operatorNames.length; i++) { const user = await prisma.user.create({ data: { name: operatorNames[i], email: `operator${i + 1}@tourlink.ke`, phone: `25470000001${i + 1}`, emailVerifiedAt: verifiedAt, phoneVerifiedAt: verifiedAt, approvalStatus: "APPROVED", passwordHash, role: Role.OPERATOR, verificationLevel: i < 3 ? VerificationLevel.TRUSTED : VerificationLevel.VERIFIED, operatorProfile: { create: { companyName: operatorNames[i], slug: operatorNames[i].toLowerCase().replaceAll(" ", "-"), description: "Thoughtful journeys led by people who know Kenya by heart.", yearsActive: 4 + i } } } }); operators.push(user); }
  const owners = []; for (let i = 0; i < 3; i++) owners.push(await prisma.user.create({ data: { name: ["Kifaru Mobility", "Jirani Rides", "Mara Fleet Co."][i], email: `owner${i + 1}@tourlink.ke`, phone: `25470000002${i + 1}`, emailVerifiedAt: verifiedAt, phoneVerifiedAt: verifiedAt, approvalStatus: "APPROVED", passwordHash, role: Role.VEHICLE_OWNER, verificationLevel: i === 0 ? VerificationLevel.TRUSTED : VerificationLevel.VERIFIED, vehicleOwnerProfile: { create: { businessName: ["Kifaru Mobility", "Jirani Rides", "Mara Fleet Co."][i] } } } }));
  const destinationRows = []; for (const [name, slug, description, imageUrl] of destinations) destinationRows.push(await prisma.destination.create({ data: { name, slug, description, imageUrl, attractions: ["Local markets", "Scenic viewpoints"], activities: ["Guided walks", "Photography"] } }));
  const categories = []; for (const name of ["Safari", "Beach", "Hiking", "Road Trip", "Adventure", "Cultural", "Wildlife", "Family", "Honeymoon", "Group Tours"]) categories.push(await prisma.tripCategory.create({ data: { name, slug: name.toLowerCase().replaceAll(" ", "-") } }));
  const tripRows = []; for (let i = 0; i < tripNames.length; i++) { const destination = destinationRows[(i + 1) % destinationRows.length]; const operator = operators[i % operators.length]; const start = new Date(Date.now() + (14 + i * 5) * 86400000); const end = new Date(start.getTime() + (2 + (i % 3)) * 86400000); tripRows.push(await prisma.trip.create({ data: { name: tripNames[i], slug: tripNames[i].toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), description: "A considered Kenyan escape with room for discovery, local stories and the kind of views that stay with you.", startingPoint: "Nairobi", endingPoint: destination.name, durationDays: Math.round((end.getTime() - start.getTime()) / 86400000), departureDate: start, returnDate: end, pricePerPerson: 14500 + i * 1850, maxTravelers: 16, availableSeats: 16 - (i % 8), pickupPoints: ["Westlands", "CBD", "JKIA"], itinerary: [{ day: 1, title: "Set out", detail: "Meet your host and travel into the landscape." }, { day: 2, title: "Go deeper", detail: "A full day to explore with your small group." }], accommodation: "A hand-picked local stay", meals: ["Breakfast", "Dinner"], transport: "Comfortable 4×4 transport", activities: ["Guided exploration", "Local dining"], includedItems: ["Transport", "Host", "Accommodation"], excludedItems: ["Personal purchases", "Travel insurance"], cancellationPolicy: "Full refund up to 7 days before departure.", featured: i < 5, operatorId: operator.id, destinationId: destination.id, categoryId: categories[i % categories.length].id, images: { create: [{ url: image(tripImages[i]), alt: tripNames[i] }] } } })); }
  const vehicleNames = ["Safari Land Cruiser KCG", "Toyota Hiace Premium", "Executive SUV 4×4", "Kifaru Safari Van", "The Roadrunner Bus", "Mara Cruiser 7-Seater", "Coastal Comfort SUV", "Nairobi City Sedan", "Explorer Minibus", "Highland Land Cruiser"];
  const vehicleRows = []; for (let i = 0; i < vehicleNames.length; i++) vehicleRows.push(await prisma.vehicle.create({ data: { name: vehicleNames[i], slug: vehicleNames[i].toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), registrationNumber: `K${String.fromCharCode(65 + i)}A ${100 + i}X`, make: i % 2 ? "Toyota" : "Land Rover", model: i % 2 ? "Hiace" : "Land Cruiser", year: 2018 + (i % 6), bodyType: i % 2 ? "Van" : "SUV", engineCc: 2800, colour: "Pearl white", seatingCapacity: [7, 12, 5, 14][i % 4], tareWeight: 2200, axles: 2, loadCapacity: 700, transmission: "Automatic", fuelType: "Diesel", airConditioning: true, fourByFour: i % 3 !== 1, driverIncluded: i % 2 === 0, pricePerDay: 6500 + i * 700, location: i % 3 === 0 ? "Nairobi" : i % 3 === 1 ? "Mombasa" : "Maasai Mara", ownerId: owners[i % owners.length].id, verificationStatus: VerificationStatus.APPROVED, images: { create: [{ url: image(["photo-1533473359331-0135ef1b58bf", "photo-1549317661-bd32c8ce0db2", "photo-1516426122078-c23e76319801"][i % 3]), alt: vehicleNames[i] }] } } }));
  for (let i = 0; i < 20; i++) { const trip = tripRows[i % tripRows.length]; const user = travelers[i % travelers.length]; const booking = await prisma.booking.create({ data: { reference: `TL-SEED-${String(i + 1).padStart(3, "0")}`, type: BookingType.TRIP, status: BookingStatus.COMPLETED, travelerId: user.id, tripId: trip.id, startDate: trip.departureDate, endDate: trip.returnDate, travelers: 2, baseAmount: trip.pricePerPerson * 2, totalAmount: trip.pricePerPerson * 2, currency: "KES", payments: { create: { merchantReference: `TL-SEED-${String(i + 1).padStart(3, "0")}`, amount: trip.pricePerPerson * 2, status: PaymentStatus.SUCCESSFUL, transactionReference: `MPESA${i + 1}`, paidAt: new Date() } } } }); await prisma.review.create({ data: { bookingId: booking.id, authorId: user.id, tripId: trip.id, rating: 4 + (i % 2), communication: 5, service: 4 + (i % 2), quality: 5, value: 4, body: ["Beautifully organised from start to finish.", "The host knew every quiet corner and made us feel at home.", "An easy booking and an even better adventure."][i % 3] } }); }
  await prisma.event.createMany({ data: [{ title: "Nairobi Travel Meetup", slug: "nairobi-travel-meetup", description: "Meet the people behind the journeys.", imageUrl: image("photo-1517457373958-b7bdd4587205"), startsAt: new Date(Date.now() + 40 * 86400000), location: "Nairobi", published: true }] });
  await prisma.blogPost.createMany({ data: [{ title: "A better way to plan a Kenyan road trip", slug: "better-way-to-plan-kenyan-road-trip", excerpt: "The little details that turn a route into a memory.", body: "Start with the feeling you want, then let the road do the rest.", imageUrl: image("photo-1539650116574-75c0c6d73f6e"), published: true }] });
  console.log("TourLink seed complete. Demo password: TourLink123!");
}
main().catch(error => { console.error(error); process.exit(1); }).finally(() => prisma.$disconnect());
