import { NextResponse } from "next/server";
import { z } from "zod";
import { getOperator } from "@/lib/operator";
import { prisma } from "@/lib/prisma";

const imageSchema = z.string().max(2_000_000).refine(value => value.startsWith("https://") || value.startsWith("data:image/"), "Invalid image");
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const updateSchema = z.object({ name: z.string().min(3).max(140).optional(), slug: z.string().min(3).max(160).optional(), description: z.string().min(20).max(4000).optional(), startingPoint: z.string().min(2).max(120).optional(), endingPoint: z.string().min(2).max(120).optional(), durationDays: z.number().int().min(1).max(60).optional(), departureDate: z.string().optional(), returnDate: z.string().optional(), pricePerPerson: z.number().int().min(0).optional(), maxTravelers: z.number().int().min(1).max(500).optional(), availableSeats: z.number().int().min(0).max(500).optional(), minTravelers: z.number().int().min(1).optional(), pickupPoints: z.array(z.string()).max(20).optional(), itinerary: z.array(z.object({ day: z.number().int().min(1), title: z.string(), detail: z.string() })).max(60).optional(), accommodation: z.string().max(500).optional(), meals: z.array(z.string()).max(20).optional(), transport: z.string().max(500).optional(), activities: z.array(z.string()).max(30).optional(), includedItems: z.array(z.string()).max(30).optional(), excludedItems: z.array(z.string()).max(30).optional(), cancellationPolicy: z.string().min(10).max(1000).optional(), destinationId: z.string().optional(), categoryId: z.string().optional(), requiredVehicleId: z.string().nullable().optional(), images: z.array(imageSchema).max(12).optional(), status: z.enum(["DRAFT", "PUBLISHED", "ARCHIVED"]).optional(), featured: z.boolean().optional(), verificationStatus: z.enum(["PENDING", "APPROVED"]).optional() });
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await getOperator(); const { id } = await params; const input = updateSchema.parse(await request.json()); const current = await prisma.trip.findFirst({ where: { id, operatorId: user.id } }); if (!current) return NextResponse.json({ error: "Trip not found" }, { status: 404 }); const { images, departureDate, returnDate, slug, ...rest } = input; const trip = await prisma.$transaction(async tx => { if (images) await tx.tripImage.deleteMany({ where: { tripId: id } }); return tx.trip.update({ where: { id }, data: { ...rest, slug: slug ? slugify(slug) : undefined, departureDate: departureDate ? new Date(departureDate) : undefined, returnDate: returnDate ? new Date(returnDate) : undefined, images: images ? { create: images.map((url, index) => ({ url, alt: input.name || current.name, sortOrder: index })) } : undefined }, include: { destination: true, category: true, requiredVehicle: true, images: true } }); }); return NextResponse.json({ trip }); } catch (error) { return NextResponse.json({ error: error instanceof z.ZodError ? "Please check the trip details." : "Trip could not be updated." }, { status: 400 }); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await getOperator(); const { id } = await params; const trip = await prisma.trip.findFirst({ where: { id, operatorId: user.id } }); if (!trip) return NextResponse.json({ error: "Trip not found" }, { status: 404 }); await prisma.trip.update({ where: { id }, data: { status: "ARCHIVED" } }); return NextResponse.json({ ok: true }); } catch { return NextResponse.json({ error: "Trip could not be archived." }, { status: 400 }); } }
