import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, Check, Fuel, MapPin, MessageCircle, Settings2, ShieldCheck, UsersRound } from "lucide-react";
import { vehicles } from "@/lib/demo-data";
import { TrustBadge, Rating } from "@/components/ui";
import { VehicleBookingForm } from "@/components/vehicle-booking-form";

export default async function VehicleDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const vehicle = vehicles.find(item => item.slug === slug) || vehicles[0];
  return <main className="min-h-screen bg-mist pb-24"><div className="container-page pt-7"><Link href="/vehicles" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16} /> All vehicles</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="relative h-[360px] overflow-hidden rounded-[26px] sm:h-[500px]"><Image src={vehicle.image} alt={vehicle.name} fill priority className="object-cover" sizes="(max-width: 1024px) 100vw, 60vw" /><div className="absolute inset-0 bg-gradient-to-t from-ink/70 to-transparent" /><div className="absolute bottom-7 left-7 text-white"><TrustBadge level={vehicle.badge} /><h1 className="display mt-3 text-4xl font-bold sm:text-6xl">{vehicle.name}</h1><p className="mt-3 flex items-center gap-2 text-sm text-white/80"><MapPin size={15} /> {vehicle.location} · {vehicle.type}</p></div></div><VehicleBookingForm vehicle={vehicle} /></div><div className="grid gap-10 py-12 lg:grid-cols-[1.15fr_.85fr]"><div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Spec icon={UsersRound} label="Seats" value={`${vehicle.seats}`} /><Spec icon={Settings2} label="Transmission" value="Automatic" /><Spec icon={Fuel} label="Fuel" value="Diesel" /><Spec icon={ShieldCheck} label="Insurance" value="Verified" /></div><h2 className="mt-10 text-xl font-black">Ready for the road</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-500">A comfortable, well-kept vehicle for the open road. Talk to the owner about routes, luggage, child seats and the kind of drive you have in mind.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><p className="flex gap-2 text-sm text-slate-600"><Check size={17} className="text-leaf" /> Air conditioning</p><p className="flex gap-2 text-sm text-slate-600"><Check size={17} className="text-leaf" /> Flexible pickup</p><p className="flex gap-2 text-sm text-slate-600"><Check size={17} className="text-leaf" /> Clean and road-ready</p><p className="flex gap-2 text-sm text-slate-600"><Check size={17} className="text-leaf" /> Driver option available</p></div></div><div className="rounded-2xl bg-white p-6 shadow-soft"><p className="eyebrow">Your vehicle host</p><h3 className="mt-3 text-lg font-black">Kifaru Mobility</h3><p className="mt-2 text-sm leading-6 text-slate-500">A trusted local fleet with a passion for making road travel simple.</p><p className="mt-5 flex items-center gap-2 text-sm font-bold"><ShieldCheck size={17} className="text-leaf" /> Identity verified</p><p className="mt-3 flex items-center gap-2 text-sm font-bold"><MessageCircle size={17} className="text-leaf" /> Replies quickly</p></div></div></div></main>;
}

function Spec({ icon: Icon, label, value }: { icon: typeof UsersRound; label: string; value: string }) { return <div className="rounded-xl bg-white p-4 shadow-soft"><Icon size={17} className="text-sun" /><p className="mt-4 text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-extrabold">{value}</p></div>; }
