import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Check, ChevronRight, HeartHandshake, ShieldCheck, Sparkles, Star, UsersRound } from "lucide-react";
import { destinations, reviews, trips, vehicles } from "@/lib/demo-data";
import { SectionHeading, TripCardView, VehicleCardView } from "@/components/ui";

export default function Home() { return <main>
  <section className="grain relative overflow-hidden bg-hero-glow text-white"><div className="container-page relative grid min-h-[650px] items-center gap-12 py-20 lg:grid-cols-[1.02fr_.98fr] lg:py-24"><div className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-2 text-[11px] font-bold uppercase tracking-[.16em] text-white/80"><Sparkles size={13} className="text-sun" /> Kenya's travel marketplace</div><h1 className="display max-w-2xl text-6xl font-bold leading-[.94] sm:text-7xl lg:text-[88px]">Go further.<br /><span className="text-sun">Feel more.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-white/72 sm:text-lg">Discover trips, hire verified vehicles, and connect with trusted tour operators. Your next story starts here.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/trips" className="rounded-full bg-sun px-6 py-3.5 text-sm font-extrabold text-ink transition hover:bg-orange-300">Explore trips <ArrowUpRight size={17} className="ml-2 inline" /></Link><Link href="/how-it-works" className="rounded-full border border-white/25 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-white/10">How it works</Link></div><div className="mt-10 flex items-center gap-5 text-xs text-white/65"><span><strong className="text-white">2,400+</strong> journeys booked</span><span className="h-1 w-1 rounded-full bg-sun" /><span><strong className="text-white">180+</strong> verified providers</span></div></div><div className="relative hidden h-[460px] lg:block"><div className="absolute right-0 top-1/2 h-[420px] w-[370px] -translate-y-1/2 rotate-3 overflow-hidden rounded-[32px] border-8 border-white/15 shadow-2xl"><Image src="https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1000&q=90" alt="Elephant in a Kenyan landscape" fill className="object-cover" priority /></div><div className="absolute bottom-8 left-2 z-10 rounded-2xl bg-white p-4 text-ink shadow-xl"><div className="mb-2 flex -space-x-2"><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-sun text-xs font-bold">AK</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-leaf text-xs font-bold text-white">DO</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-lagoon text-xs font-bold text-white">+</span></div><p className="text-xs font-extrabold">Good company, guaranteed.</p><p className="mt-1 text-[10px] text-slate-500">Join a community of curious travelers</p></div></div></div></section>

  <section className="container-page pt-32"><SectionHeading eyebrow="Start somewhere beautiful" title="Where will you go next?" body="From big five mornings to slow coastal afternoons, find a trip that feels like yours." href="/destinations" /><div className="hide-scrollbar -mx-3 flex gap-4 overflow-x-auto px-3 pb-5 md:grid md:grid-cols-4 md:overflow-visible">{destinations.map((destination, i) => <Link href={`/trips?destination=${encodeURIComponent(destination.name)}`} key={destination.name} className={`group relative min-w-[245px] overflow-hidden rounded-2xl ${i === 0 ? "md:col-span-2 md:row-span-2 md:min-h-[378px]" : "h-[180px]"}`}><Image src={destination.image} alt={destination.name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 245px, 30vw" /><div className="absolute inset-0 bg-gradient-to-t from-ink/75 via-ink/10 to-transparent" /><div className="absolute bottom-4 left-4 text-white"><h3 className="text-xl font-black">{destination.name}</h3><p className="mt-1 text-xs text-white/70">{destination.count}</p></div></Link>)}</div></section>

  <section className="container-page py-24"><SectionHeading eyebrow="Made for the moment" title="Trips worth the detour" body="Small groups, thoughtful itineraries, and hosts who know the way." href="/trips" /><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{trips.slice(0, 3).map(trip => <TripCardView key={trip.id} trip={trip} />)}</div></section>

  <section className="bg-sand py-24"><div className="container-page"><SectionHeading eyebrow="The right ride changes everything" title="Move your way" body="Compare verified vehicles for game drives, road trips, airport runs and everything in between." href="/vehicles" linkLabel="Browse vehicles" /><div className="grid gap-5 md:grid-cols-3">{vehicles.map(vehicle => <VehicleCardView key={vehicle.id} vehicle={vehicle} />)}</div></div></section>

  <section className="container-page py-24"><div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow mb-3">Travel, with more trust</p><h2 className="display text-4xl font-bold leading-tight sm:text-5xl">Every good journey starts with a little confidence.</h2><p className="mt-5 max-w-md text-sm leading-7 text-slate-500">We bring the important bits into one place, so you can spend less time chasing details and more time looking out the window.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-lagoon/10 text-lagoon"><ShieldCheck size={20} /></span><div><h3 className="text-sm font-extrabold">Verified people</h3><p className="mt-1 text-xs leading-5 text-slate-500">Real checks, visible badges and honest reviews.</p></div></div><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-sun/15 text-sun"><HeartHandshake size={20} /></span><div><h3 className="text-sm font-extrabold">Human support</h3><p className="mt-1 text-xs leading-5 text-slate-500">Chat with providers before you book.</p></div></div></div><Link href="/how-it-works" className="mt-8 inline-flex items-center gap-2 text-sm font-extrabold text-lagoon">Why TourLink <ChevronRight size={16} /></Link></div><div className="relative min-h-[390px] overflow-hidden rounded-[28px] bg-ink"><Image src="https://images.unsplash.com/photo-1535338454770-8be927b5a00b?auto=format&fit=crop&w=1200&q=85" alt="Kenyan safari landscape" fill className="object-cover opacity-85" /><div className="absolute inset-0 bg-gradient-to-t from-ink/80 via-transparent to-transparent" /><div className="absolute bottom-7 left-7 right-7 text-white"><p className="display text-3xl font-bold">One platform.<br /><span className="text-sun">Endless journeys.</span></p></div></div></div></section>

  <section className="bg-ink py-24 text-white"><div className="container-page"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow mb-3 text-sun">Good words from the road</p><h2 className="display text-4xl font-bold sm:text-5xl">Stories they brought home.</h2></div><div className="hidden items-center gap-2 text-sm font-bold text-white/60 sm:flex"><Star size={16} fill="#ee8d3b" color="#ee8d3b" /> 4.9 average rating</div></div><div className="grid gap-5 md:grid-cols-3">{reviews.map(review => <div key={review.name} className="rounded-2xl border border-white/10 bg-white/5 p-6"><div className="flex gap-1 text-sun"><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /></div><p className="mt-6 min-h-[100px] text-sm leading-7 text-white/75">“{review.quote}”</p><div className="mt-6 flex items-center gap-3 border-t border-white/10 pt-5"><span className={`grid h-9 w-9 place-items-center rounded-full text-xs font-black text-white ${review.color}`}>{review.initials}</span><div><p className="text-xs font-extrabold">{review.name}</p><p className="mt-1 text-[11px] text-white/45">{review.trip}</p></div></div></div>)}</div></div></section>

  <section className="container-page py-20"><div className="relative overflow-hidden rounded-[28px] bg-sun px-7 py-12 text-ink sm:px-14"><div className="relative z-10 max-w-xl"><p className="eyebrow text-ink/60">Your local knowledge matters</p><h2 className="display mt-3 text-4xl font-bold leading-tight sm:text-5xl">Have a trip to share?</h2><p className="mt-4 max-w-md text-sm leading-6 text-ink/70">Join a growing community of thoughtful operators and vehicle owners making travel across East Africa more accessible.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/register?role=operator" className="rounded-full bg-ink px-5 py-3 text-sm font-extrabold text-white">Become an operator</Link><Link href="/register?role=vehicle" className="rounded-full border border-ink/25 px-5 py-3 text-sm font-extrabold">List your vehicle</Link></div></div><UsersRound className="absolute -bottom-12 -right-7 h-64 w-64 rotate-12 text-ink/10" /></div></section>
</main>; }
