import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const vehicleSchema = z.object({ name: z.string().min(2).max(120), registrationNumber: z.string().min(2).max(30), make: z.string().min(2).max(60), model: z.string().min(2).max(60), year: z.number().int().min(1980).max(new Date().getFullYear() + 1), bodyType: z.string().min(2).max(60), seatingCapacity: z.number().int().min(1).max(100), transmission: z.string().min(2).max(30), fuelType: z.string().min(2).max(30), pricePerDay: z.number().int().min(0), location: z.string().min(2).max(120), airConditioning: z.boolean().default(false), fourByFour: z.boolean().default(false), driverIncluded: z.boolean().default(false), images: z.array(z.string().max(2_000_000)).max(12).default([]) });
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
async function owner() { const user = await getCurrentUser(); return user?.role === "VEHICLE_OWNER" ? user : null; }
export async function GET() { const user = await owner(); if (!user) return NextResponse.json({ error: "Vehicle owner access required" }, { status: 403 }); const vehicles = await prisma.vehicle.findMany({ where: { ownerId: user.id }, include: { images: true }, orderBy: { createdAt: "desc" } }); return NextResponse.json({ vehicles }); }
export async function POST(request: Request) { const user = await owner(); if (!user) return NextResponse.json({ error: "Vehicle owner access required" }, { status: 403 }); try { const input = vehicleSchema.parse(await request.json()); const base = slugify(`${input.name}-${input.registrationNumber}`); const { images, ...details } = input; const vehicle = await prisma.vehicle.create({ data: { ...details, slug: `${base}-${Date.now().toString(36)}`, ownerId: user.id, status: "DRAFT", verificationStatus: "PENDING", images: { create: images.map((url, index) => ({ url, alt: input.name })) } }, include: { images: true } }); return NextResponse.json({ vehicle }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof z.ZodError ? "Please complete all vehicle details." : "Vehicle could not be created." }, { status: 400 }); } }
