"use client";
import Link from "next/link";
import { BarChart3, Bell, BookOpen, CalendarDays, CarFront, ChevronRight, Clock3, CreditCard, Heart, LayoutDashboard, LogOut, MessageCircle, Plus, Settings, ShieldCheck, Star, TrendingUp, UserRound, UsersRound } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";

const traveler = [{ href: "/dashboard", label: "Overview", icon: LayoutDashboard }, { href: "/dashboard/bookings", label: "My bookings", icon: BookOpen }, { href: "/dashboard/upcoming", label: "Upcoming trips", icon: CalendarDays }, { href: "/dashboard/past", label: "Past trips", icon: Clock3 }, { href: "/dashboard/favorites", label: "Favorites", icon: Heart }, { href: "/dashboard/payments", label: "Payments", icon: CreditCard }, { href: "/dashboard/messages", label: "Messages", icon: MessageCircle }, { href: "/dashboard/notifications", label: "Notifications", icon: Bell }];
const operator = [{ href: "/dashboard", label: "Overview", icon: LayoutDashboard }, { href: "/dashboard/listings", label: "Trips", icon: CarFront }, { href: "/dashboard/listings/new", label: "Create trip", icon: Plus }, { href: "/dashboard/bookings", label: "Bookings", icon: BookOpen }, { href: "/dashboard/customers", label: "Customers", icon: UsersRound }, { href: "/dashboard/vehicles", label: "Vehicles", icon: CarFront }, { href: "/dashboard/messages", label: "Messages", icon: MessageCircle }, { href: "/dashboard/reviews", label: "Reviews", icon: Star }, { href: "/dashboard/earnings", label: "Earnings", icon: TrendingUp }, { href: "/dashboard/payments", label: "Payments", icon: CreditCard }, { href: "/dashboard/verification", label: "Verification", icon: ShieldCheck }, { href: "/dashboard/analytics", label: "Analytics", icon: BarChart3 }];
const vehicleOwner = [{ href: "/dashboard", label: "Overview", icon: LayoutDashboard }, { href: "/dashboard/vehicles", label: "Add and manage vehicles", icon: CarFront }, { href: "/dashboard/bookings", label: "Manage bookings", icon: BookOpen }, { href: "/dashboard/messages", label: "Chat with operators", icon: MessageCircle }, { href: "/dashboard/earnings", label: "View earnings", icon: TrendingUp }, { href: "/dashboard/reviews", label: "View ratings", icon: Star }, { href: "/dashboard/verification", label: "Request verification", icon: ShieldCheck }];

export function DashboardShell({ children, user }: { children: React.ReactNode; user: { name: string; email: string; role: string; verificationLevel: string } }) { const pathname = usePathname(); const router = useRouter(); const links = user.role === "TRAVELER" ? traveler : user.role === "VEHICLE_OWNER" ? vehicleOwner : operator; const roleLabel = user.role === "TRAVELER" ? "Traveler" : user.role === "OPERATOR" ? "Tour operator" : "Vehicle owner"; async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.push("/"); router.refresh(); } return <main className="min-h-screen bg-mist pb-20 sm:pb-0"><div className="container-page grid gap-7 py-7 lg:grid-cols-[230px_1fr]"><aside className="hidden lg:block"><div className="sticky top-7"><div className="rounded-2xl bg-ink p-5 text-white"><div className="grid h-12 w-12 place-items-center rounded-full bg-sun text-lg font-black text-ink">{user.name.split(" ").map(x => x[0]).join("").slice(0, 2)}</div><p className="mt-4 text-sm font-extrabold">{user.name}</p><p className="mt-1 text-[11px] text-white/50">{roleLabel}</p><span className="mt-4 inline-flex items-center gap-1 rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-bold"><ShieldCheck size={12} className="text-sun" /> {user.verificationLevel}</span></div><nav className="mt-5 grid gap-1">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${pathname === href ? "bg-lagoon text-white" : "text-slate-500 hover:bg-white hover:text-ink"}`}><Icon size={17} />{label}{label === "Notifications" && <span className="ml-auto rounded-full bg-sun px-1.5 text-[10px] text-ink">3</span>}</Link>)}</nav><div className="mt-5 border-t border-slate-200 pt-4"><Link href="/dashboard/profile" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-500 hover:bg-white"><UserRound size={17} />Profile</Link><Link href="/dashboard/settings" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-500 hover:bg-white"><Settings size={17} />Settings</Link><button onClick={logout} className="mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-500 hover:bg-white"><LogOut size={17} />Log out</button></div></div></aside><section className="min-w-0"><div className="mb-5 flex items-center justify-between lg:hidden"><div><p className="text-sm font-extrabold">{user.name}</p><p className="text-[10px] text-slate-400">{roleLabel}</p></div><button onClick={logout} className="rounded-full bg-white px-4 py-2 text-xs font-bold shadow-soft">Log out</button></div>{children}</section></div></main>; }
export function StatCard({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: "calendar" | "star" | "message" | "trend" }) { const Icon = { calendar: CalendarDays, star: Star, message: MessageCircle, trend: BarChart3 }[icon]; return <div className="rounded-2xl bg-white p-5 shadow-soft"><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sand text-lagoon"><Icon size={17} /></span><ChevronRight size={16} className="text-slate-300" /></div><p className="mt-5 text-2xl font-black text-ink">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-[11px] text-leaf">{detail}</p></div>; }
