import Link from "next/link";
import { BarChart3, CarFront, CheckCircle2, CircleDollarSign, Clock3, Mail, Star, TrendingUp, UsersRound } from "lucide-react";

type Customer = { id: string; name: string; email: string; phone: string | null; bookings: number; spent: number };
export function OperatorCustomers({ customers }: { customers: Customer[] }) { return <Panel eyebrow="People you host" title="Customers"><div className="grid gap-3">{customers.length ? customers.map(customer => <div key={customer.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-sand text-sm font-black text-ink">{customer.name.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="text-sm font-extrabold">{customer.name}</p><p className="mt-1 truncate text-xs text-slate-500">{customer.email}{customer.phone ? ` · ${customer.phone}` : ""}</p></div><div className="text-right"><p className="text-sm font-black">{customer.bookings} bookings</p><p className="mt-1 text-[10px] text-slate-400">KES {customer.spent.toLocaleString("en-KE")} spent</p></div><Mail size={15} className="text-slate-300" /></div>) : <Empty text="Customers appear after your first booking." />}</div></Panel>; }

export function OperatorVehicles({ vehicles }: { vehicles: { id: string; name: string; location: string; seats: number; price: number; verified: string }[] }) { return <Panel eyebrow="Your transport network" title="Vehicles"><div className="grid gap-3 sm:grid-cols-2">{vehicles.map(vehicle => <div key={vehicle.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-lagoon/10 text-lagoon"><CarFront size={19} /></span><span className="rounded-full bg-leaf/10 px-2 py-1 text-[10px] font-black text-leaf">{vehicle.verified}</span></div><h3 className="mt-4 text-sm font-extrabold">{vehicle.name}</h3><p className="mt-1 text-xs text-slate-500">{vehicle.location} · {vehicle.seats} seats</p><p className="mt-4 text-sm font-black">KES {vehicle.price.toLocaleString("en-KE")} <span className="text-[10px] font-normal text-slate-400">/ day</span></p></div>)}</div></Panel>; }

type ReviewRow = { id: string; rating: number; body: string; author: string; trip: string; createdAt: string };
export function OperatorReviews({ reviews }: { reviews: ReviewRow[] }) { return <Panel eyebrow="What travelers say" title="Reviews"><div className="grid gap-3">{reviews.length ? reviews.map(review => <article key={review.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-center justify-between"><div className="flex gap-1 text-sun">{[1, 2, 3, 4, 5].map(star => <Star key={star} size={13} fill={star <= review.rating ? "currentColor" : "none"} />)}</div><span className="text-[10px] text-slate-400">{review.author}</span></div><p className="mt-4 text-sm leading-6 text-slate-600">&quot;{review.body}&quot;</p><p className="mt-3 text-[10px] font-bold text-slate-400">{review.trip} · {new Date(review.createdAt).toLocaleDateString("en-KE")}</p></article>) : <Empty text="Reviews from completed trips will appear here." />}</div></Panel>; }

type PaymentRow = { id: string; reference: string; item: string; amount: number; currency: string; status: string; date: string };
export function OperatorPayments({ payments }: { payments: PaymentRow[] }) { return <Panel eyebrow="Money in motion" title="Payments"><div className="grid gap-3">{payments.length ? payments.map(payment => <div key={payment.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sand text-lagoon"><CircleDollarSign size={17} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{payment.item}</p><p className="mt-1 text-[10px] text-slate-400">{payment.reference} · {new Date(payment.date).toLocaleDateString("en-KE")}</p></div><div className="text-right"><p className="text-sm font-black">{payment.currency} {payment.amount.toLocaleString("en-KE")}</p><p className={`mt-1 text-[10px] font-bold ${payment.status === "SUCCESSFUL" ? "text-leaf" : "text-[#a45913]"}`}>{payment.status}</p></div></div>) : <Empty text="Payment records will appear when travelers book your trips." />}</div></Panel>; }

export function OperatorEarnings({ gross, projected, commission, bookings }: { gross: number; projected: number; commission: number; bookings: number }) { return <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={CircleDollarSign} label="Gross bookings" value={`KES ${gross.toLocaleString("en-KE")}`} detail="Before platform fees" /><Metric icon={TrendingUp} label="Projected revenue" value={`KES ${projected.toLocaleString("en-KE")}`} detail="Future non-cancelled bookings" /><Metric icon={TrendingUp} label="Your earnings" value={`KES ${(gross - commission).toLocaleString("en-KE")}`} detail="Estimated provider payout" /><Metric icon={CheckCircle2} label="Completed bookings" value={String(bookings)} detail="Ready for payout" /></div><Panel eyebrow="How you earn" title="Earnings breakdown"><div className="grid gap-4 text-sm"><div className="flex justify-between border-b border-slate-100 pb-4"><span className="text-slate-500">Gross booking value</span><strong>KES {gross.toLocaleString("en-KE")}</strong></div><div className="flex justify-between border-b border-slate-100 pb-4"><span className="text-slate-500">Projected revenue</span><strong className="text-lagoon">KES {projected.toLocaleString("en-KE")}</strong></div><div className="flex justify-between border-b border-slate-100 pb-4"><span className="text-slate-500">TourLink commission</span><strong className="text-sun">- KES {commission.toLocaleString("en-KE")}</strong></div><div className="flex justify-between text-lg"><span className="font-black">Estimated provider earnings</span><strong>KES {(gross - commission).toLocaleString("en-KE")}</strong></div></div></Panel></div>; }

export function OperatorAnalytics({ trips, bookings, reviews, rating }: { trips: number; bookings: number; reviews: number; rating: number }) { return <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={CarFront} label="Published trips" value={String(trips)} detail="Active in marketplace" /><Metric icon={UsersRound} label="Bookings" value={String(bookings)} detail="Across your trips" /><Metric icon={Star} label="Reviews" value={String(reviews)} detail="From completed journeys" /><Metric icon={BarChart3} label="Average rating" value={rating.toFixed(1)} detail="Out of 5" /></div><Panel eyebrow="Performance at a glance" title="Keep the momentum"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-sand p-5"><p className="text-xs font-bold text-slate-500">Conversion focus</p><p className="mt-3 text-2xl font-black">Reply fast</p><p className="mt-2 text-xs leading-5 text-slate-500">Fast replies build confidence before travelers book.</p></div><div className="rounded-xl bg-lagoon p-5 text-white"><p className="text-xs font-bold text-white/60">Trust focus</p><p className="mt-3 text-2xl font-black">Stay verified</p><p className="mt-2 text-xs leading-5 text-white/60">Keep business and trip details current.</p></div><div className="rounded-xl bg-sun p-5"><p className="text-xs font-bold text-ink/60">Growth focus</p><p className="mt-3 text-2xl font-black">Add variety</p><p className="mt-2 text-xs leading-5 text-ink/60">Offer a mix of durations and price points.</p></div></div></Panel></div>; }

export function OperatorOverview({ trips, bookings, pending, gross }: { trips: number; bookings: number; pending: number; gross: number }) { return <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={CarFront} label="Published trips" value={String(trips)} detail="Live in marketplace" /><Metric icon={UsersRound} label="Total bookings" value={String(bookings)} detail="Across your catalogue" /><Metric icon={Clock3} label="Needs response" value={String(pending)} detail="Pending confirmations" /><Metric icon={CircleDollarSign} label="Gross earnings" value={`KES ${gross.toLocaleString("en-KE")}`} detail="Before commission" /></div><div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Panel eyebrow="Your marketplace" title="Keep journeys moving"><div className="grid gap-3"><Link href="/dashboard/listings/new" className="flex items-center justify-between rounded-xl bg-sand p-4"><span><strong className="block text-sm">Create a new trip</strong><span className="mt-1 block text-xs text-slate-500">Share another reason to explore.</span></span><CarFront size={19} className="text-lagoon" /></Link><Link href="/dashboard/bookings" className="flex items-center justify-between rounded-xl border border-slate-100 p-4"><span><strong className="block text-sm">Review pending bookings</strong><span className="mt-1 block text-xs text-slate-500">Respond quickly and build trust.</span></span><Clock3 size={19} className="text-sun" /></Link><Link href="/dashboard/analytics" className="flex items-center justify-between rounded-xl border border-slate-100 p-4"><span><strong className="block text-sm">Check your performance</strong><span className="mt-1 block text-xs text-slate-500">See ratings, bookings and momentum.</span></span><BarChart3 size={19} className="text-lagoon" /></Link></div></Panel><div className="rounded-2xl bg-ink p-6 text-white"><p className="eyebrow text-sun">Provider promise</p><h2 className="display mt-2 text-3xl font-bold">The best journeys feel effortless.</h2><p className="mt-4 text-sm leading-6 text-white/60">Keep your availability current, answer messages with care, and let travelers see the person behind the trip.</p><Link href="/dashboard/company" className="mt-7 inline-flex rounded-full bg-sun px-4 py-3 text-xs font-extrabold text-ink">Update company profile</Link></div></div></div>; }

export function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <div className="rounded-2xl bg-white p-5 shadow-soft sm:p-7"><p className="eyebrow">{eyebrow}</p><h2 className="mt-1 text-2xl font-black">{title}</h2><div className="mt-7">{children}</div></div>; }
function Metric({ icon: Icon, label, value, detail }: { icon: typeof CircleDollarSign; label: string; value: string; detail: string }) { return <div className="rounded-2xl bg-white p-5 shadow-soft"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sand text-lagoon"><Icon size={17} /></span><p className="mt-5 text-2xl font-black">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-[11px] text-leaf">{detail}</p></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-mist p-6 text-center text-sm text-slate-500">{text}</p>; }
