import { BadgeCheck, CalendarDays, CarFront, ChevronRight, MapPin, ShieldCheck, Star, UsersRound } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { formatKES, type TripCard, type VehicleCard } from "@/lib/demo-data";
import { CompareButton } from "@/components/compare-button";

export function TrustBadge({ level = "VERIFIED" }: { level?: "VERIFIED" | "TRUSTED" }) { return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-extrabold tracking-[.08em] ${level === "TRUSTED" ? "bg-sun/15 text-[#a45913]" : "bg-leaf/15 text-leaf"}`}><BadgeCheck size={12} /> {level}</span>; }
export function Rating({ value, reviews }: { value: number; reviews: number }) { return <span className="inline-flex items-center gap-1 text-xs font-bold text-ink"><Star size={13} fill="#ee8d3b" color="#ee8d3b" /> {value} <span className="font-normal text-slate-400">({reviews})</span></span>; }
export function SectionHeading({ eyebrow, title, body, href, linkLabel = "View all" }: { eyebrow: string; title: string; body?: string; href?: string; linkLabel?: string }) { return <div className="mb-7 flex items-end justify-between gap-5"><div><p className="eyebrow mb-2">{eyebrow}</p><h2 className="display text-3xl font-bold leading-tight text-ink sm:text-[42px]">{title}</h2>{body && <p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">{body}</p>}</div>{href && <Link href={href} className="hidden shrink-0 items-center gap-1 text-sm font-extrabold text-lagoon sm:flex">{linkLabel}<ChevronRight size={16} /></Link>}</div>; }
export function TripCardView({ trip }: { trip: TripCard }) { return <Link href={`/trips/${trip.slug}`} className="group overflow-hidden rounded-2xl bg-white shadow-soft transition duration-300 hover:-translate-y-1 hover:shadow-card"><div className="relative h-52 overflow-hidden"><Image src={trip.image} alt={trip.name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 640px) 90vw, 33vw" /><div className="absolute inset-0 bg-gradient-to-t from-ink/55 to-transparent" /><div className="absolute left-4 top-4"><TrustBadge level={trip.badge} /></div><CompareButton slug={trip.slug} /><div className="absolute bottom-4 left-4 text-white"><p className="text-xs font-semibold text-white/75">{trip.category}</p><h3 className="mt-1 text-xl font-extrabold tracking-tight">{trip.name}</h3></div></div><div className="p-4"><div className="mb-4 flex items-center justify-between"><span className="flex items-center gap-1.5 text-xs font-semibold text-slate-500"><MapPin size={14} className="text-sun" /> {trip.destination}</span><Rating value={trip.rating} reviews={trip.reviews} /></div><div className="flex items-end justify-between"><div><span className="text-xs text-slate-400">from</span><p className="text-lg font-black text-ink">{formatKES(trip.price)} <span className="text-xs font-medium text-slate-400">/ person</span></p></div><span className="rounded-full bg-sand px-3 py-1.5 text-xs font-bold text-ink">{trip.days} days</span></div></div></Link>; }
export function VehicleCardView({ vehicle }: { vehicle: VehicleCard }) { return <Link href={`/vehicles/${vehicle.slug}`} className="group overflow-hidden rounded-2xl bg-white shadow-soft transition duration-300 hover:-translate-y-1 hover:shadow-card"><div className="relative h-48 overflow-hidden"><Image src={vehicle.image} alt={vehicle.name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 640px) 90vw, 33vw" /><div className="absolute left-4 top-4"><TrustBadge level={vehicle.badge} /></div></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-extrabold tracking-tight text-ink">{vehicle.name}</h3><p className="mt-1 text-xs text-slate-500">{vehicle.type} · {vehicle.location}</p></div><Rating value={vehicle.rating} reviews={vehicle.reviews} /></div><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold text-slate-500"><span className="rounded-full bg-mist px-2.5 py-1"><UsersRound size={12} className="mr-1 inline" />{vehicle.seats} seats</span>{vehicle.fourByFour && <span className="rounded-full bg-mist px-2.5 py-1">4×4</span>}{vehicle.driver && <span className="rounded-full bg-mist px-2.5 py-1">Driver included</span>}</div><p className="mt-4 text-lg font-black text-ink">{formatKES(vehicle.price)} <span className="text-xs font-medium text-slate-400">/ day</span></p></div></Link>; }
export function EmptyState({ icon: Icon = MapPin, title, body }: { icon?: typeof MapPin; title: string; body: string }) { return <div className="grid place-items-center rounded-3xl border border-dashed border-slate-200 bg-white px-6 py-16 text-center"><span className="mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-sand text-sun"><Icon /></span><h3 className="font-extrabold text-ink">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">{body}</p></div>; }
