"use client";
import Link from "next/link";
import { CalendarDays, Loader2, ShieldCheck } from "lucide-react";
import { useState } from "react";
import type { VehicleCard } from "@/lib/demo-data";
import { formatKES } from "@/lib/demo-data";

export function VehicleBookingForm({ vehicle }: { vehicle: VehicleCard }) { const [startDate, setStartDate] = useState("2026-09-20"); const [endDate, setEndDate] = useState("2026-09-22"); const [driverRequired, setDriverRequired] = useState(vehicle.driver); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); async function book() { setLoading(true); setMessage(""); const response = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ vehicleId: vehicle.slug, startDate, endDate, driverRequired }) }); const data = await response.json(); setLoading(false); if (response.status === 401) { setMessage("Please log in to continue."); return; } setMessage(response.ok ? `Booking ${data.booking.reference} created. Continue to payment in your dashboard.` : data.error); } return <div className="h-fit rounded-2xl bg-white p-6 shadow-card sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs text-slate-400">from</p><p className="text-2xl font-black">{formatKES(vehicle.price)} <span className="text-xs font-medium text-slate-400">/ day</span></p></div><span className="rounded-full bg-leaf/10 px-3 py-1.5 text-xs font-bold text-leaf">Available</span></div><div className="mt-6 grid gap-3"><DateField label="Pickup date" value={startDate} onChange={setStartDate} /><DateField label="Return date" value={endDate} onChange={setEndDate} /></div><label className="mt-4 flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-xs font-bold"><input type="checkbox" checked={driverRequired} onChange={event => setDriverRequired(event.target.checked)} className="h-4 w-4 accent-lagoon" /> Include a driver</label><button onClick={book} disabled={loading} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-sun px-4 py-3.5 text-sm font-extrabold text-ink">{loading && <Loader2 size={16} className="animate-spin" />} Request this vehicle</button>{message && <p className="mt-3 rounded-lg bg-sand p-3 text-center text-xs font-bold">{message} {message === "Please log in to continue." && <Link className="underline" href="/login">Log in</Link>}</p>}<p className="mt-4 flex justify-center gap-1.5 text-center text-[11px] text-slate-400"><ShieldCheck size={14} className="text-leaf" /> Secure booking · Verified owner</p></div>; }
function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="rounded-xl border border-slate-200 p-3"><span className="block text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</span><span className="mt-1 flex items-center gap-2"><CalendarDays size={16} className="text-sun" /><input type="date" value={value} onChange={event => onChange(event.target.value)} className="w-full text-sm font-bold outline-none" /></span></label>; }
