import Link from "next/link";
import { ArrowUpRight, BarChart3, CalendarCheck2, CarFront, CheckCircle2, CircleDollarSign, Clock3, ImagePlus, MessageCircle, Settings2, ShieldCheck, Star, TrendingUp, UserPlus, UserRound, UsersRound, XCircle } from "lucide-react";

const capabilities = [
  { label: "Register", description: "Open a vehicle-owner account.", href: "/register?role=VEHICLE_OWNER", icon: UserPlus },
  { label: "Create profile", description: "Add your owner details and bio.", href: "/dashboard/profile", icon: UserRound },
  { label: "Add vehicles", description: "Build and manage your fleet.", href: "/dashboard/vehicles", icon: CarFront },
  { label: "Upload vehicle photos", description: "Show travelers your vehicles.", href: "/dashboard/vehicles", icon: ImagePlus },
  { label: "Add vehicle specifications", description: "Record seats, fuel, body type and features.", href: "/dashboard/vehicles", icon: Settings2 },
  { label: "Set price per day", description: "Control daily rental pricing.", href: "/dashboard/vehicles", icon: CircleDollarSign },
  { label: "Set availability", description: "Publish dates when vehicles can be booked.", href: "/dashboard/vehicles", icon: CalendarCheck2 },
  { label: "Accept booking requests", description: "Confirm suitable traveler requests.", href: "/dashboard/bookings", icon: CheckCircle2 },
  { label: "Reject booking requests", description: "Decline requests you cannot fulfill.", href: "/dashboard/bookings", icon: XCircle },
  { label: "Manage bookings", description: "Review dates, travelers and booking status.", href: "/dashboard/bookings", icon: UsersRound },
  { label: "Chat with tour operators", description: "Build partnerships through direct chat.", href: "/dashboard/messages", icon: MessageCircle },
  { label: "View earnings", description: "Track gross bookings and estimated payout.", href: "/dashboard/earnings", icon: TrendingUp },
  { label: "View ratings", description: "Read traveler feedback and ratings.", href: "/dashboard/reviews", icon: Star },
  { label: "Request verification", description: "Submit business and identity details.", href: "/dashboard/verification", icon: ShieldCheck },
];

export function VehicleOwnerOverview({ vehicles, bookings, pending, gross }: { vehicles: number; bookings: number; pending: number; gross: number }) { return <div className="grid gap-6"><div><p className="eyebrow">Vehicle owner workspace</p><h1 className="display mt-1 text-4xl font-bold">Run your vehicle business.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Register, list your fleet, respond to bookings and build trusted relationships with TourLink operators.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Active vehicles" value={String(vehicles)} detail="Your listed fleet" icon={CarFront} /><Metric label="Vehicle bookings" value={String(bookings)} detail="Across your fleet" icon={UsersRound} /><Metric label="Needs response" value={String(pending)} detail="Pending confirmations" icon={Clock3} /><Metric label="Gross earnings" value={`KES ${gross.toLocaleString("en-KE")}`} detail="Before commission" icon={CircleDollarSign} /></div><section className="rounded-2xl bg-white p-5 shadow-soft sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Owner capabilities</p><h2 className="mt-1 text-2xl font-black">Everything in one place.</h2></div><Link href="/dashboard/vehicles" className="inline-flex items-center gap-1 text-xs font-extrabold text-lagoon">Open fleet <ArrowUpRight size={14} /></Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><CapabilityList /></div></section><section className="rounded-2xl bg-ink p-6 text-white sm:p-7"><p className="eyebrow text-sun">Grow with TourLink</p><h2 className="mt-1 text-2xl font-black">Make every vehicle easier to trust.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Keep your profile, photos, specifications, availability and verification details current so operators can confidently work with your fleet.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/dashboard/verification" className="inline-flex items-center gap-2 rounded-full bg-sun px-4 py-2.5 text-xs font-black text-ink">Request verification <ArrowUpRight size={14} /></Link><Link href="/dashboard/messages" className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2.5 text-xs font-black text-white">Chat with operators <MessageCircle size={14} /></Link></div></section></div>; }

function CapabilityList() { return <>{capabilities.map(({ label, description, href, icon: Icon }) => <Link key={label} href={href} className="group flex items-start gap-3 rounded-xl border border-slate-100 p-4 transition hover:border-lagoon hover:bg-mist"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-sand text-lagoon"><Icon size={17} /></span><span className="min-w-0 flex-1"><strong className="block text-sm text-ink">{label}</strong><span className="mt-1 block text-xs leading-5 text-slate-500">{description}</span></span><ArrowUpRight size={15} className="mt-1 shrink-0 text-slate-300 transition group-hover:text-lagoon" /></Link>)}</>; }

export function VehicleOwnerAnalytics({ vehicles, bookings, reviews, rating }: { vehicles: number; bookings: number; reviews: number; rating: number }) { return <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Active vehicles" value={String(vehicles)} detail="Listed fleet" icon={CarFront} /><Metric label="Bookings" value={String(bookings)} detail="Across your fleet" icon={UsersRound} /><Metric label="Reviews" value={String(reviews)} detail="Traveler feedback" icon={Star} /><Metric label="Average rating" value={rating.toFixed(1)} detail="Out of 5" icon={BarChart3} /></div><section className="rounded-2xl bg-white p-6 shadow-soft"><p className="eyebrow">Fleet performance</p><h2 className="mt-1 text-2xl font-black">Build a more dependable fleet.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-500">Keep vehicle availability, verification documents and service quality current to earn stronger traveler confidence.</p></section></div>; }

export function VehicleOwnerEarnings({ gross, projected, commission, bookings }: { gross: number; projected: number; commission: number; bookings: number }) { return <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={CircleDollarSign} label="Gross bookings" value={`KES ${gross.toLocaleString("en-KE")}`} detail="Before platform fees" /><Metric icon={TrendingUp} label="Projected revenue" value={`KES ${projected.toLocaleString("en-KE")}`} detail="Future non-cancelled bookings" /><Metric icon={TrendingUp} label="Estimated earnings" value={`KES ${(gross - commission).toLocaleString("en-KE")}`} detail="After commission" /><Metric icon={UsersRound} label="Completed bookings" value={String(bookings)} detail="Ready for payout" /></div><section className="rounded-2xl bg-white p-6 shadow-soft"><p className="eyebrow">Earnings breakdown</p><div className="mt-6 grid gap-4 text-sm"><div className="flex justify-between border-b border-slate-100 pb-4"><span className="text-slate-500">Gross booking value</span><strong>KES {gross.toLocaleString("en-KE")}</strong></div><div className="flex justify-between border-b border-slate-100 pb-4"><span className="text-slate-500">Projected revenue</span><strong className="text-lagoon">KES {projected.toLocaleString("en-KE")}</strong></div><div className="flex justify-between border-b border-slate-100 pb-4"><span className="text-slate-500">TourLink commission</span><strong className="text-sun">- KES {commission.toLocaleString("en-KE")}</strong></div><div className="flex justify-between text-lg"><span className="font-black">Estimated earnings</span><strong>KES {(gross - commission).toLocaleString("en-KE")}</strong></div></div></section></div>; }

function Metric({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: React.ElementType }) { return <div className="rounded-2xl bg-white p-5 shadow-soft"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sand text-lagoon"><Icon size={17} /></span><p className="mt-5 text-2xl font-black">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-[11px] text-leaf">{detail}</p></div>; }
