import { NextResponse } from "next/server";
import { z } from "zod";
import { getOperator } from "@/lib/operator";
import { prisma } from "@/lib/prisma";

const imageSchema = z.string().max(2_000_000).refine(value => value.startsWith("https://") || value.startsWith("data:image/"), "Invalid image");
const tripSchema = z.object({ name: z.string().min(3).max(140), slug: z.string().min(3).max(160).optional(), description: z.string().min(20).max(4000), startingPoint: z.string().min(2).max(120), endingPoint: z.string().min(2).max(120), durationDays: z.number().int().min(1).max(60), departureDate: z.string(), returnDate: z.string(), pricePerPerson: z.number().int().min(0), maxTravelers: z.number().int().min(1).max(500), availableSeats: z.number().int().min(0).max(500), minTravelers: z.number().int().min(1).default(1), pickupPoints: z.array(z.string().min(1).max(120)).max(20), itinerary: z.array(z.object({ day: z.number().int().min(1), title: z.string().min(1).max(100), detail: z.string().min(1).max(500) })).max(60), accommodation: z.string().max(500).optional(), meals: z.array(z.string().max(100)).max(20), transport: z.string().max(500).optional(), activities: z.array(z.string().max(150)).max(30), includedItems: z.array(z.string().max(150)).max(30), excludedItems: z.array(z.string().max(150)).max(30), cancellationPolicy: z.string().min(10).max(1000), destinationId: z.string(), categoryId: z.string(), requiredVehicleId: z.string().nullable().optional(), images: z.array(imageSchema).max(12), status: z.enum(["DRAFT", "PUBLISHED"]).default("DRAFT"), featured: z.boolean().default(false), verificationStatus: z.enum(["PENDING", "APPROVED"]).default("PENDING") });
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export async function GET() { try { const user = await getOperator(); const trips = await prisma.trip.findMany({ where: { operatorId: user.id }, include: { destination: true, category: true, images: { orderBy: { sortOrder: "asc" } }, _count: { select: { bookings: true, reviews: true } } }, orderBy: { updatedAt: "desc" } }); return NextResponse.json({ trips }); } catch { return NextResponse.json({ error: "Operator access required" }, { status: 403 }); } }
export async function POST(request: Request) { try { const user = await getOperator(); const input = tripSchema.parse(await request.json()); const destination = await prisma.destination.findUnique({ where: { id: input.destinationId } }); const category = await prisma.tripCategory.findUnique({ where: { id: input.categoryId } }); if (!destination || !category) return NextResponse.json({ error: "Choose a valid destination and category." }, { status: 400 }); const baseSlug = slugify(input.slug || input.name); const slug = input.slug ? baseSlug : `${baseSlug}-${Date.now().toString(36)}`; const trip = await prisma.trip.create({ data: { ...input, slug, departureDate: new Date(input.departureDate), returnDate: new Date(input.returnDate), operatorId: user.id, images: { create: input.images.map((url, index) => ({ url, alt: input.name, sortOrder: index })) } }, include: { destination: true, category: true, requiredVehicle: true, images: true } }); return NextResponse.json({ trip }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof z.ZodError ? "Please complete all trip details." : "Trip could not be created. The slug may already be in use." }, { status: 400 }); } }
