import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { createTripBooking, createVehicleBooking } from "@/lib/booking";
import { prisma } from "@/lib/prisma";

export async function GET() { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Authentication required" }, { status: 401 }); const bookings = await prisma.booking.findMany({ where: { travelerId: user.id }, include: { trip: { include: { destination: true, images: true, operator: { select: { name: true, verificationLevel: true, operatorProfile: true } } } }, vehicle: { include: { images: true, owner: { select: { name: true, verificationLevel: true, vehicleOwnerProfile: true } } } }, payments: { orderBy: { createdAt: "desc" }, take: 1 }, reviews: true }, orderBy: { startDate: "desc" } }); return NextResponse.json({ bookings }); }

export async function POST(request: Request) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Authentication required" }, { status: 401 }); try { const body = await request.json(); const common = { userId: user.id, startDate: new Date(body.startDate) }; if (body.tripId) { const input = z.object({ tripId: z.string().min(1), travelers: z.number().int().min(1).max(100), startDate: z.string(), pickupLocation: z.string().max(120).optional() }).parse(body); const booking = await createTripBooking({ ...input, ...common, startDate: new Date(input.startDate) }); return NextResponse.json({ booking }, { status: 201 }); } const input = z.object({ vehicleId: z.string().min(1), startDate: z.string(), endDate: z.string(), driverRequired: z.boolean().default(false), pickupLocation: z.string().max(120).optional() }).parse(body); const booking = await createVehicleBooking({ ...input, ...common, startDate: new Date(input.startDate), endDate: new Date(input.endDate) }); return NextResponse.json({ booking }, { status: 201 }); } catch (error) { const code = error instanceof Error ? error.message : ""; const messages: Record<string, string> = { NOT_ENOUGH_SEATS: "Not enough seats available for this trip.", VEHICLE_BOOKED: "This vehicle is already booked for those dates.", INVALID_DATES: "Return date must be after pickup date.", TRIP_UNAVAILABLE: "This trip is no longer available.", VEHICLE_UNAVAILABLE: "This vehicle is no longer available." }; return NextResponse.json({ error: messages[code] || "Unable to create booking." }, { status: 400 }); } }
