import Link from "next/link";
import { ArrowUpRight, CalendarDays, Heart, MessageCircle, Star, TrendingUp } from "lucide-react";
import { StatCard } from "@/components/dashboard-shell";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { OperatorOverview } from "@/components/operator-extra-views";
import { VehicleOwnerOverview } from "@/components/vehicle-owner-overview";

export default async function DashboardPage() { const currentUser = await getCurrentUser(); if (currentUser?.role === "OPERATOR") { const [trips, bookings] = await Promise.all([prisma.trip.findMany({ where: { operatorId: currentUser.id }, select: { status: true } }), prisma.booking.findMany({ where: { trip: { operatorId: currentUser.id }, status: { notIn: ["CANCELLED", "REFUNDED"] } }, select: { status: true, totalAmount: true } })]); return <OperatorOverview trips={trips.filter(trip => trip.status === "PUBLISHED").length} bookings={bookings.length} pending={bookings.filter(booking => booking.status === "PENDING").length} gross={bookings.reduce((total, booking) => total + booking.totalAmount, 0)} />; } if (currentUser?.role === "VEHICLE_OWNER") { const [vehicles, bookings] = await Promise.all([prisma.vehicle.findMany({ where: { ownerId: currentUser.id, status: { not: "ARCHIVED" } }, select: { status: true } }), prisma.booking.findMany({ where: { vehicle: { ownerId: currentUser.id }, status: { notIn: ["CANCELLED", "REFUNDED"] } }, select: { status: true, totalAmount: true } })]); return <VehicleOwnerOverview vehicles={vehicles.filter(vehicle => vehicle.status === "PUBLISHED").length} bookings={bookings.length} pending={bookings.filter(booking => booking.status === "PENDING").length} gross={bookings.reduce((total, booking) => total + booking.totalAmount, 0)} />; } return <TravelerOverview />; }

function TravelerOverview() { return <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Upcoming journeys" value="2" detail="Next: Maasai Mara · 14 Aug" icon="calendar" /><StatCard label="Saved experiences" value="8" detail="2 added this week" icon="star" /><StatCard label="Messages" value="3" detail="1 needs your reply" icon="message" /><StatCard label="Travelled together" value="KES 84,400" detail="Across 4 bookings" icon="trend" /></div><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl bg-white p-6 shadow-soft"><div className="flex items-center justify-between"><div><p className="eyebrow">Coming up</p><h2 className="mt-1 text-xl font-black">Your next journeys</h2></div><Link href="/dashboard/bookings" className="text-xs font-extrabold text-lagoon">All bookings <ArrowUpRight size={14} className="ml-1 inline" /></Link></div><div className="mt-6 rounded-xl bg-sand p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold text-slate-500">14 Aug · 3 days</p><h3 className="mt-2 text-xl font-black">Maasai Mara golden hour</h3><p className="mt-2 text-sm text-slate-500">Savanna & Soul · 2 travelers</p></div><CalendarDays className="text-lagoon" /></div><Link href="/dashboard/upcoming" className="mt-5 inline-flex items-center gap-2 text-xs font-black text-lagoon">View itinerary <ArrowUpRight size={14} /></Link></div></section><section className="rounded-2xl bg-ink p-6 text-white"><p className="eyebrow text-sun">Your travel rhythm</p><h2 className="display mt-2 text-3xl font-bold">Keep a little room for wonder.</h2><p className="mt-4 text-sm leading-6 text-white/60">Save experiences, message hosts and build your next escape at your own pace.</p><div className="mt-7 flex gap-2"><Heart size={17} className="text-sun" /><Star size={17} className="text-sun" /><TrendingUp size={17} className="text-sun" /></div></section></div></div>; }
